# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d42ef76456d7891048e30afbfd8259c78bc2e5a4caaebb2e8b8b62cd671322724eeb16418466bccecdf9fbb0cc7e37e9c9f029bde2ef0d0dbe9fdd43be248b7a

test:
  secret_key_base: ffbcd5c513b9c8bdd5cb350ad8df069977280f61bf5b943579200bd92120df2e8512a98c084793f7bf6a820bc408ee6182dc5174514c16544e7b96776632a3a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
